### ISSUE TITLE
Host key verification failed. fatal: The remote end hung up unexpectedly

### ISSUE THREAD

**Issue by exdestroyer** [ExpandedFronts/Revisr#44] opened 2015-03-16 06:17 UTC
hi, author.
I get a error when I try to push or pull.

error messages:
"Host key verification failed.
fatal: The remote end hung up unexpectedly"

It seems that Revisr will generate a .ssh directory when I first click push and pull. But when I see that directory it is empty. So I generate a ssh key by "sudo -u apache ssh-keygen -t rsa".And add the pub key to my Bitbucket account. Change directory and files owner to apache. But the error still turn out.
You seem to be active in this support.So please check this out quickly.
Thanks!

**Comment by mgshaw** [comment] 2015-03-16 18:09
Closing this as not a bug/feature request. Please use the wordpress support forums for support requests.

**Closed by mgshaw** 2015-03-16 18:09 UTC
